#!D:\GitHub\Begging_Django_API_With_React_build_Django4_Web_APIs\virtualenv\Scripts\python.exe

import todo

if __name__ == '__main__':
	import argparse
	parser = argparse.ArgumentParser(description='Find TODOs')
	parser.add_argument('names', metavar='NAMES', type=str, nargs='*',
	                   help='TODO names (any of which is a match). TODO(sam) = sam')
	parser.add_argument('--count', action='store_true',
	                   help='only print the count',
	                   default=False)
	# TODO: content: whole db, diff, or changed files
	args = parser.parse_args()

	todo.interactive(match_names=args.names, show_count=args.count)